### PR TITLE
Added CPU Load Average for vmware esxi 6 template and duplicated it o…

### PR DESCRIPTION
**Pull request by roemer2201**
…ver for vmware esxi 7

### CODE REVIEW

**Comment by bonomani** [comment]
Thanks very much! 

You write that you duplicate the template. Is there a reason for you not to make something that match both like the following?: 
vendor	: vmware
model	: esxi6-esxi7
snmpver	: 2
sysdesc : VMware ESXi (?:6|7)

and rename the template
vmware-esxi[67]

**Comment by roemer2201** [comment]
Well, you are right, I thought that there would be differences occurring in the oid. But I tested it and it seems to work fine. I'll fix this to your suggestion.

**Comment by roemer2201** [comment]
This should work now, right?

**Comment by bonomani** [comment]
Yes, and also I change my mind. I tell you previously that I would like have a monitoring of each CPU, but now I think that the average is better in a vmware context. But let me check first how it looks like...

**Comment by bonomani** [comment]
Clever work, simple transform, html trick in message: really cool! will merge it very soon

**Comment by roemer2201** [comment]
2021-06-17_08h31_56
2021-06-17_08h33_19

This is how it looks like.

One thought I just had: I put the ID for the average behind the ID for the last core. Wouldn't it be better, if it is stored on ID 0 ? This way, if for whatever reason, the amount of cores changes, would not have an negative effect on the data and graphing. Imagine a dropped number of cores in a machine (like from turning of HT/SMT): This would cause the average to be added to one of the existing graphs mixing it with single core data.

**Comment by bonomani** [comment]
Yes, would be better with ID0, it is why I wrote a comment yesterday and create the issue #39 : it simulate exaclty that and what we could do with just transform for this problem. And currently there is just one transform missing the ADD transform (and the SORT is not documented as I was no sure it was the best way to do is but it is a SORT by value. Also, as there is quite a lot of transforms this give me new ideas (I also just post them in the same issue)

**Comment by roemer2201** [comment]
Today I dived into the problem and I think currently there is no way around putting it at the end. The core problem is the following: showgraph.cgi and/or showgraph.sh only accept positional (numerical) values in the form of an ID (or better call offset). The order is dervied from the sort of the rrd-files. If you sort them, numeric rrd's come first and the rest in alphabetical order. The Showgraph mechanism accesses the RRDs for display via the HTML GET "first" and "count" where first is the index/offset number. In case we name the average CPU Load "0", this will create an RRD file named zero and therefore it appears first in the sort mechanism. Unfortunately it will also become the Index 1 (instead of 0) and will push CPU1 back to position 2 and finally push the last CPU out of the display range. See:
2021-06-18_13h38_50
2021-06-18_13h39_18

This means this problem is only partially fixable by adding the AVG as the last index in the table. Yes, it will be displayed at the end of all other single core graphs automatically, but it will not fix the issue with the removed CPU cores. It would only work, if the RRD-Files of the missing cores are deleted from the filesystem. But this is the solution for both scenarios (ID 0 or CPU-Count+1).

A solution might be changing the showgraph mechanism, but this would be xymon territory and not devmon.

Just for the complete picture, one can set HTTP-GET "first=0", but this does not access "CPU 0", it has a special meaning of laying every CPU graph on top of each other:
2021-06-18_14h14_39

**Comment by bonomani** [comment]
Yes, I also think that for now, this is not possible: 
- There is no way to add 2 tables in a page : Xymon RRD module for devmon parse the data and stop after the  1rs table....have to change "c" code.
- The other way is to intergate it in the existing table, so we stay, with 1 table. I dont know if did understand what I wrote in the issue #39 , but it is an an elegant manner and a quite easy way to do it, as creating this ADD transform that is missing should not be that difficult.
- But by now your solution is the best, as such I will intergrate it as I said very soon (sorry I am working on a big change now, so need a few days)

**Comment by bonomani** [comment]
Another diffficulty is that Xymon only send the graph in an ALPHA order. I workaround this problem, with some padding, but it not that elegant. Also this force the SORT transform only work with alpha PRI_OID...which is not optimal for indexes...

**Pull request merged**
